version: "3.0"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10

  haystack:
    build:
      context: .
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - DOCUMENTSTORE_PARAMS_PORT=9200
      - DENSE_RETRIEVER_MODEL=panosgriz/covid-el-paraphrase-multilingual-MiniLM-L12-v2
      - RERANKER_MODEL=amberoad/bert-multilingual-passage-reranking-msmarco
      - EXTRACTIVE_READER_MODEL=panosgriz/mdeberta-v3-base-squad2-covid-el-small
      - GENERATIVE_MODEL=ilsp/Meltemi-7B-Instruct-v1.5
      - CUDA_VISIBLE_DEVICES=0
    depends_on:
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]